### ISSUE TITLE
nas: Offline host causes http analysis to fail

### ISSUE THREAD

**Issue by ikstream** [4elta/recon#40]
Using the http analyzer causes an `AttributeError` on a file without results. The host seemingly went offline after the service scan before running recon. The resulting file can be seen at the end of the issue.

./analyze.py -i ../test/logs/recon http
```
Traceback (most recent call last):
  File "/recon/./analyze.py", line 151, in <module>
    main()
  File "/recon/./analyze.py", line 148, in main
    process(parser.parse_args())
  File "/recon/./analyze.py", line 80, in process
    services = analyzer.analyze(files)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/recon/analyzers/http/__init__.py", line 27, in analyze
    services = self.parser.parse_files(files[self.parser_name])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/recon/analyzers/__init__.py", line 24, in parse_files
    self.parse_file(path)
  File "/recon/analyzers/http/nmap.py", line 58, in parse_file
    for port_node in ports_node.iter('port'):
                     ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'iter'
```

cat ../test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.log
```
# Nmap 7.94 scan initiated Mon Feb 30 10:10:10 1010 as: nmap -Pn -v -sV -p 80 "--script=banner,ssl-cert,http* and not (brute or broadcast or dos or external or http-slowloris* or fuzzer)" -oN /test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.log -oX /test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.xml 10.0.0.7
Nmap scan report for 10.0.0.7 [host down]
Read data files from: /usr/bin/../share/nmap
# Nmap done at Mon Feb 30 10:10:10 1010 -- 1 IP address (0 hosts up) scanned in 1.71 seconds

```

**Comment by ikstream** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>
<!-- Nmap 7.94 scan initiated Mon Jun 26 18:20:29 2023 as: nmap -Pn -v -sV -p 80 &quot;-&#45;script=banner,ssl-cert,http* and not (brute or broadcast or dos or external or http-slowloris* or fuzzer)&quot; -oN /test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.log -oX /test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.xml 10.0.0.7 -->
<nmaprun scanner="nmap" args="nmap -Pn -v -sV -p 80 &quot;-&#45;script=banner,ssl-cert,http* and not (brute or broadcast or dos or external or http-slowloris* or fuzzer)&quot; -oN /test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.log -oX /test/logs/recon/10.0.0.7/services/http,tcp,80,10.0.0.7,nmap.xml 10.0.0.7" start="1687796429" startstr="Mon Jun 26 18:20:29 2023" version="7.94" xmloutputversion="1.05">
<scaninfo type="syn" protocol="tcp" numservices="1" services="80"/>
<verbose level="1"/>
<debugging level="0"/>
<taskbegin task="NSE" time="1687796429"/>
<taskend task="NSE" time="1687796429"/>
<taskbegin task="NSE" time="1687796429"/>
<taskend task="NSE" time="1687796429"/>
<taskbegin task="ARP Ping Scan" time="1687796429"/>
<taskend task="ARP Ping Scan" time="1687796430" extrainfo="1 total hosts"/>
<host><status state="down" reason="no-response" reason_ttl="0"/>
<address addr="10.0.0.7" addrtype="ipv4"/>
</host>
<taskbegin task="NSE" time="1687796430"/>
<taskend task="NSE" time="1687796430"/>
<taskbegin task="NSE" time="1687796430"/>
<taskend task="NSE" time="1687796430"/>
<runstats><finished time="1687796430" timestr="Fri Feb 30 10:10:10 1010" summary="Nmap done at Fri Feb 30 10:10:10 1010; 1 IP address (0 hosts up) scanned in 1.71 seconds" elapsed="1.71" exit="success"/><hosts up="0" down="1" total="1"/>
</runstats>
</nmaprun>
```
