### ISSUE TITLE
Analyser Exception on analyising PSK TLS ciphers with nmap

### ISSUE THREAD

**Issue by Yuuichi89** [4elta/recon#73]
The nmap analyzer within the "Develop" branch currently throws the following exception when analyzing TLS ciphers that use PSK:
>Traceback (most recent call last):
>
>   File "/usr/local/bin/analyze", line 281, in <module>
>     main()
>   File "/usr/local/bin/analyze", line 278, in main
>     process(parser.parse_args())
>   File "/usr/local/bin/analyze", line 209, in process
>     analyze_service(
>   File "/usr/local/bin/analyze", line 64, in analyze_service
>     services = analyzer.analyze(files)
>                ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/kali/tools/recon/analyzers/tls/__init__.py", line 95, in analyze
>     services = self.parser.parse_files(files[self.parser_name])
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/kali/tools/recon/analyzers/__init__.py", line 75, in parse_files
>     self.parse_file(path)
>   File "/home/kali/tools/recon/analyzers/tls/nmap.py", line 116, in parse_file
>     self._parse_cipher_suites(script_node, service)
>   File "/home/kali/tools/recon/analyzers/tls/nmap.py", line 239, in _parse_cipher_suites
>     self._parse_protocol_node(
>   File "/home/kali/tools/recon/analyzers/tls/nmap.py", line 209, in _parse_protocol_node
>     kex_info = cipher_node.find('./elem[@ key="kex_info"]').text
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'text'

This seems to be because the kex_info element is not present for PSK.
Here is an example nmap xml cipher table with PSK where this occurred:

> \<table key="ciphers"\>
> \<table\>
> \<elem key="kex_info"\>secp256r1\</elem\>
> \<elem key="name"\>TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA\</elem\>
> \<elem key="strength"\>A\</elem\>
> \</table\>
> \<table\>
> \<elem key="kex_info"\>secp256r1\</elem\>
> \<elem key="name"\>TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256\</elem\>
> \<elem key="strength"\>A\</elem\>
> \</table\>
> \<table\>
> \<elem key="kex_info"\>secp256r1\</elem\>
> \<elem key="name"\>TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA\</elem\>
> \<elem key="strength"\>A\</elem\>
> \</table\>
> \<table\>
> \<elem key="kex_info"\>secp256r1\</elem\>
> \<elem key="name"\>TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384\</elem\>
> \<elem key="strength"\>A\</elem\>
> \</table\>
> \<table\>
> \<elem key="kex_info"\>secp256r1\</elem\>
> \<elem key="name"\>TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256\</elem\>
> \<elem key="strength"\>A\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_AES_128_CBC_SHA\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_AES_128_CBC_SHA256\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_AES_128_GCM_SHA256\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_AES_256_CBC_SHA\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_AES_256_CBC_SHA384\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_AES_256_GCM_SHA384\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \<table\>
> \<elem key="name"\>TLS_PSK_WITH_CHACHA20_POLY1305_SHA256\</elem\>
> \<elem key="strength"\>unknown\</elem\>
> \</table\>
> \</table\>

**Comment by Yuuichi89** [comment]
Thanks for the quick fix :)
